const HOME_PAGE_PATH = './public/index.html';
const ENCODING_UTF8 = 'utf-8';
const TODO_LISTS_PLACEHOLDER = '____TODO_LISTS____';
const TODO_LISTS_PATH = './data/todo_lists.json';
const LIST_ID_PLACEHOLDER = '____LIST_ID____';
const ADD_ITEMS_PAGE_PATH = './public/add_items.html';
const EDIT_ITEM_PAGE_PATH = './public/edit_items.html';
const ITEM_CONTENT_PLACEHOLDER = '____ITEM_CONTENT____';
const ITEM_ID_PLACEHOLDER = '____ITEM_ID____';
const ERROR_404 = 'Resource not found';
const EDIT_LIST_PAGE_PATH = './public/edit_list.html';
const LIST_DESCRIPTION_PLACEHOLDER = '____LIST_DESCRIPTION____';
const LIST_TITLE_PLACEHOLDER = '____LIST_TITLE____';
const DATA_DIRECTORY = './data';
const PUBLIC_DIRECTORY = './public';
const DEFAULT_TODO_LISTS_JSON = '{"lists":[], "latestListID":0}';

module.exports = {
  HOME_PAGE_PATH,
  ENCODING_UTF8,
  TODO_LISTS_PLACEHOLDER,
  TODO_LISTS_PATH,
  LIST_ID_PLACEHOLDER,
  ADD_ITEMS_PAGE_PATH,
  ERROR_404,
  EDIT_ITEM_PAGE_PATH,
  ITEM_CONTENT_PLACEHOLDER,
  ITEM_ID_PLACEHOLDER,
  EDIT_LIST_PAGE_PATH,
  LIST_DESCRIPTION_PLACEHOLDER,
  LIST_TITLE_PLACEHOLDER,
  DATA_DIRECTORY,
  PUBLIC_DIRECTORY,
  DEFAULT_TODO_LISTS_JSON
};
